<?php
declare(strict_types=1);
require_once( __DIR__ . '/../../vendor/autoload.php');
use Core\Config\Config;
use Core\Cache\Memcached;

$cache  = new Memcached(Config::getMemcacheHost(), Config::getMemcachePort());
if (!$cache->isSet('chain_length')) {
    echo 'set to 50 m<br>';
    $cache->set('chain_length', 50);
} else {
    echo "is alredy set to = " . $cache->get('chain_length') . " m<br>";
    if ($cache->isSet('OBJ_ANCHOR')) {
        echo "Ancor Obj is set<br>";
    } else {
        echo "try to set Ancor<br>";
    }
}

