<?php
use Nmea\Config\Config;
require_once( __DIR__ . '/../../vendor/autoload.php');
?>
<html lang="en">
  <head>
    <title>Anchor</title>
      <link href="./css/anchor.css" type="text/css" rel="stylesheet" />
      <script src="https://code.highcharts.com/maps/highmaps.js"></script>
      <script src="https://code.highcharts.com/maps/modules/data.js"></script>
      <script src="https://code.highcharts.com/maps/modules/tiledwebmap.js"></script>
      <script src="https://code.highcharts.com/maps/modules/exporting.js"></script>
      <script src="https://code.highcharts.com/maps/modules/offline-exporting.js"></script>
      <script src="https://code.highcharts.com/maps/modules/accessibility.js"></script>
      <script src="https://code.highcharts.com/maps/modules/debugger.js"></script>
      <script type="module" src="js/anchor/series.js"></script>
  </head>
  <body>
    <audio id="alarmSound" src="sound/alertAlarm.wav" preload="auto"></audio>
    <div class="main">
        <div id="container"></div>
        <div class="row d-flex justify-content-center main">
            <div class="btn-line text-center">
                <input type="number" name="ancorMeter" id="ancorMeter" min="0" max="100" class="form-input"/>
                <label for="ancorMeter" class="mt-4">m</label>
                <button id="setAncor" class="btn btn-outline-secondary">Set Ancor</button>
                <button id="ancorAlarmSound" class="btn btn-outline-secondary" onclick="playSound()">Alarm Signal</button>
            </div>
        </div>
    </div>
    <script>
        const host ='<?= Config::getApiServerHost(); ?>';
    </script>
    <script src="js/anchor.js"></script>
  </body>
</html>
