<!DOCTYPE html>
<html>

<head>
    <title>Wind speed</title>
    <link rel="stylesheet" type="text/css" href="graph.css">
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/highcharts-more.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/data.js"></script>
    <script src="https://code.highcharts.com/modules/accessibility.js"></script>
</head>
<figure class="highcharts-figure">
    <div id="container"></div>
</figure>
<script src="graph.js"></script>
</html>