<!DOCTYPE html>
<html lang="en">

<head>
    <title>Wind speed</title>
    <link rel="stylesheet" type="text/css" href="css/graph.css">
    <script src="js/highcharts/highcharts.js"></script>
    <script src="js/highcharts/highcharts-more.js"></script>
    <script src="js/highcharts/exporting.js"></script>
    <script src="js/highcharts/export-data.js"></script>
    <script src="js/highcharts/data.js"></script>
    <script src="js/highcharts/accessibility.js"></script>
</head>
<figure class="highcharts-figure">
    <div id="container"></div>
</figure>
<script src="js/graph.js"></script>
</html>