<?php
error_reporting(E_ALL);
ini_set('display_errors', '1');
use \Nmea\Config\Config;
use \Nmea\Database\Database;
use \Nmea\Database\Mapper\WindroseMapper;
require_once( __DIR__ . '/../../vendor/autoload.php');

Database::getInstance()->init(Config::getMariadbHost(), Config::getMariadbPort(),Config::getMariadbUser(),Config::getMariadbPassword(), Config::getMariadbName());
$mapper = new WindroseMapper(Database::getInstance());
$entity = $mapper->getWindroseEntity();

?>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/highcharts-more.js"></script>
<script src="https://code.highcharts.com/modules/data.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>
<script src="https://code.highcharts.com/themes/dark-unica.js"></script>
<link rel="stylesheet" type="text/css" href="css/windrose.css" />

<figure class="highcharts-figure">
    <div id="container"></div>
    <p class="highcharts-description">

    </p>
</figure>

<div style="display:none">
    <table id="freq" border="0" cellspacing="0" cellpadding="0">
        <tr nowrap bgcolor="#CCCCFF">
            <th colspan="9" class="hdr">Table of Frequencies (percent)</th>
        </tr>
        <tr nowrap bgcolor="#CCCCFF">
            <th class="freq">Direction</th>
            <th class="freq">< 1 bf</th>
            <th class="freq">1 bf</th>
            <th class="freq">2 bf</th>
            <th class="freq">3 bf</th>
            <th class="freq">4 bf</th>
            <th class="freq">5 bf</th>
            <th class="freq">6 bf</th>
            <th class="freq">7 bf</th>
            <th class="freq">8 bf</th>
            <th class="freq">9 bf</th>
            <th class="freq">10 bf</th>
            <th class="freq">11 bf</th>
            <th class="freq">>12 bf</th>
            <th class="freq">Total</th>
        </tr>
        <?= $entity->getTableData() ?>
    </table>
</div>
<script src="js/windrose.js"></script>



