name: CI-latest

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6
      - name: Install deps
        run: |
          apt install php-bcmath
      - name: PHPUnit Tests
        uses: php-actions/phpunit@master
        env:
          TEST_NAME: Scarlett
        with:
          version: 9.6
          php_version: 8.3
          extensions: bcmath
          bootstrap: vendor/autoload.php
          configuration: test/phpunit.xml
          args: --coverage-text
