name: CI-latest

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: |
          sudo apt-get install -y php-bcmath
          sudo apt-get install memcached
          sudo systemctl start memcached
          sudo apt-get install -y libmemcached-dev zlib1g-dev libssl-dev
          sudo apt-get install -y php-memcached
          sudo php -m
      - uses: php-actions/composer@v6
       
      - name: PHPUnit Tests
        uses: php-actions/phpunit@master
        env:
          TEST_NAME: Scarlett
        with:
          version: 11.2
          php_version: 8.3
          extensions: bcmath memcached
          bootstrap: vendor/autoload.php
          configuration: test/phpunit.xml
          args: --coverage-text
